# https://github.com/martialonline/workflow-status/blob/master/action.yml
name: "Workflow Status Action"
description: "Trigger events like notifications or alerts using the workflow status"

outputs:
  status:
    description: "Returns either success or failed or cancelled as workflow status"
    value: ${{ steps.workflow-status.outputs.status }}
runs:
  using: "composite"
  steps:
    - id: workflow-status
      run: |
        url="${{ github.event.repository.html_url} }/repos"
        repo="${ github.event.repository.name }}"
        run_id="${{ github.run_id }}"
        token="${{ secret.GITHUB_TOKEN }}"
        failure=$(curl -s -H "Authorization: token ${token}" "${url}/${repo}/actions/runs/${run_id}/jobs" | \
        jq -r '.jobs[] | select(.status == "completed" and .conclusion == "failure").conclusion' | \
        wc -l)
        cancelled=$(curl -s -H "Authorization: token ${token}" "${url}/${repo}/actions/runs/${run_id}/jobs" | \
        jq -r '.jobs[] | select(.status == "completed" and .conclusion == "cancelled").conclusion' | \
        wc -l)
        if [ "${failure}" -gt 0 ]; then
          status="failure"
        elif [ "${cancelled}" -gt 0 ]; then
          status="cancelled"
        else 
          status="success"
        fi
        
        echo "status=${status}" >> $GIHUB_OUTPUT
      shell: bash

