name: dispacher job
on: 
  workflow_dispatch:
    inputs:
      environment:
        description: which environment to deploy
        required: true
        type: choice
        options:
          - development
          - production

jobs:
  deploy-manually-prepare:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: before deploy
        run: git name-rev --name-only HEAD

  deploy-manually-real:
    needs:
      - deploy-manually-prepare
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    steps:
      - name: hoge run
        run: echo deploy to ${{ inputs.environment }}
     
      - name: create tag
        run: |
          TAG=v$(jq -r < package.json .version)
          git tag $TAG
          git push origin $TAG
          

    
