name: 'matrix preview'
on: [push]

permissions:
  contents: read

jobs:
  depende-job:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3

      - name: run ls -la depended job
        run: ls -la
     
  # テストすること。matrixで一部が失敗した場合リスタートできるのか
  matrix-job:
    runs-on: ubuntu-latest
    needs:
      - depende-job
    concurrency:
      group: "${{ github.workflow }} @ ${{ matrix.name }}"
      cancel-in-progress: false

    strategy:
      # https://docs.github.com/ja/actions/using-jobs/using-a-matrix-for-your-jobs#handling-failures
    #  fail-fast: true
      matrix:
        include:
          - name: first
            value: 1
            sleep: 30
          - name: seconde
            value: 2
            sleep: 30
          - name: third
            value: 1
            sleep: 30
    steps:
      - uses: actions/checkout@v3

      - name: run ls -la
        run: ls -la
   
      - name: ${{ matrix.name }} step adn sleep
#        run:  test ${{ matrix.value }} == 1
        run: echo ${{ matrix.name }} && sleep ${{ matrix.sleep }}

      - name: check materix value
        run: echo "name ${{ matrix.name }} value ${{ matrix.value }}"

      - name: check materix value
        run: echo "name ${{ matrix.name }} value ${{ matrix.value }}"
      
      - name: aieuo
        run: test ${{ matrix.value }} == 1
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: setup nx and cache
        uses: ./.github/actions/yarn-nx-cache/
        with:
          fetch-depth: 0

      - name: check
        run: |
          node --version
          yarn --version
          echo $NX_CACHE_DIRECTORY
 
      - name: check write
        run: ls -la .nx-cache
 
      - name: check
        run: |
          node --version
          yarn --version
          echo $NX_CACHE_DIRECTORY
      
      - name: run nx
        run: yarn run -T nx run-many --target build

      - name: run nx secondtime
        run: yarn run -T nx run-many --target build

  notification:
    needs:
      - matrix-job
    if: always()
    uses: ./.github/workflows/slack-notification.yml
    secrets: inherit

