name: Slack Notification

on:
  workflow_call:
    inputs:
      success:
        required: true
        type: boolean
      failure:
        required: true
        type: boolean
      cancelled:
        required: true
        type: boolean
jobs:
  slack-notification:
    runs-on: ubuntu-latest
    steps:
      - name: make success payload param
        if: input.success
        run: |
          echo "ICON_EMOJI=:gift:" >> $GITHUB_ENV
          echo "COLOR=#34eb34" >> $GITHUB_ENV
          echo "TEXT=SUCCESS" >> $GITHUB_ENV
 
      - name: make failure payload param
        if: input.failure
        run: |
          echo "ICON_EMOJI=:exclamation:" >> $GITHUB_ENV
          echo "COLOR=#eb4034" >> $GITHUB_ENV
          echo "TEXT=FAILED" >> $GITHUB_ENV
 
      - name: make cancel payload param
        if: input.cancelled
        run: |
          echo "ICON_EMOJI=:grey_exclamation:" >> $GITHUB_ENV
          echo "COLOR=#949494" >> $GITHUB_ENV
          echo "TEXT=CANCELLED" >> $GITHUB_ENV
 
      - name: send to webhook
        uses: slackapi/slack-github-action@v1.23.0
        with:
          # For posting a rich message using Block Kit
          payload: |
            {
              "icon_emoji": "${{ env.ICON_EMOJI }}",
              "username": "${{ github.event.repository.name }}",
              "text": "GitHub Action result: ${{ env.TEXT }}",
              "attachments": [
                {
                  "color": "${{ env.COLOR }}",
                  "author_name": "${{ github.actor }}",
                  "author_icon": "${{ github.event.sender.avatar_url }}",
                  "text": "${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}"
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
